//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosValoraciones
    {
        public int id_comentario { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public string comentario_texto { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> comentario_fecha { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
