//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCarrito
    {
        public int id_detalle { get; set; }
        public Nullable<int> carrito_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> agregado_fecha { get; set; }
    
        public virtual CarritoCompras CarritoCompras { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
